# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='filename',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
