# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_review_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='is_accepted',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'with penalization'), (2, 'yes')], default=2),
        ),
    ]
