# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import testovac.tasks.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160510_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(blank=True, default=testovac.tasks.utils.default_contest_start_end_time, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(blank=True, default=testovac.tasks.utils.default_contest_start_end_time, null=True),
        ),
    ]
